<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-cart"><?php //echo $this->getHeaderText() ?></h4>
        <div class="form-buttons"><?php// echo $this->getButtonsHtml() ?></div>
    </div>
	<?php //echo $this->getLayout()->createblock('salessurvey/adminhtml_reminder_edit_tab_addproducts_items_grid')->setTemplate('sales/order/create/items/grid.phtml')->toHtml(); ?>
</div>