<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<div class="block block-video">
    <div class="block-content">
        <object width="100%" height="450"><param name="movie" value="http://www.youtube.com/v/<?php echo $_product->getVideo() ?>?hl=en_US&amp;version=3"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/<?php echo $_product->getVideo() ?>?hl=en_US&amp;version=3" type="application/x-shockwave-flash" width="100%" height="450" allowscriptaccess="always" allowfullscreen="true"></embed></object>
    </div>
</div>



