<link href="{{skin url='/css/custom1.css'}}" rel="stylesheet" media="all" type="text/css" />
<div class="custom-cms">
<div class="section-1">
<h1>Save 50% Over Custom Glass With Prosto Frameless Showers</h1>
</div>
<div class="section-2">
<div class="custom-left"><img alt="" src="{{media url="wysiwyg/prosto-Logo.png"}}" /></div>
<div class="custom-right">
<p>Finally an affordable way to order glass shower doors. Prosto shower glass is a frameless shower door system. The galss is cut in bulk with 3 different kinds of panels. Use the panels in combination with one another and we have over 1000 different size combos. Get $49 shipping on all shower enclosures- order today and get it in 2 weeks!</p>
</div>
</div>
<div class="section-3">
<div class="custom-left"><iframe width="560" height="315" src="https://www.youtube.com/embed/6PrLxk6TwBw?rel=0&autohide=1&autoplay=1&showinfo=0" frameborder="0" allowfullscreen="0"></iframe>
</div>
<div class="custom-right">
<h2>Prosto is the Simple Solution</h2>
<ul>
<li>1000s of Sizes available</li>
<li>3 beautiful hardware finishes</li>
<li>Corners, Enaclaves, Single Doors</li>
</ul>
<a class="button-shower" href="#"><img alt="" src="{{media url="wysiwyg/button.png"}}" /></a></div>
</div>
<div class="section-4">
<h2>Affordable Framless Showers:</h2>
<p>Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content.</p>
<p>Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content.</p>
<p>Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content.</p>
<p>Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content. Lorem Ipsum is simple dummy content.</p>
</div>
</div>