<?php
require_once('../app/Mage.php'); //Path to Magento
umask(0);
Mage::app();
// Get the rule by ID
$rule = Mage::getModel('salesrule/rule')->load(2);
 
$generator = Mage::getModel('salesrule/coupon_massgenerator');
 
$generator->setDash( !empty($parameters['dash_every_x_characters'])? (int) $parameters['dash_every_x_characters'] : 0);
$generator->setLength( !empty($parameters['length'])? (int) $parameters['length'] : 6);
$generator->setPrefix( !empty($parameters['prefix'])? $parameters['prefix'] : '');
$generator->setSuffix( !empty($parameters['suffix'])? $parameters['suffix'] : '');
 
$rule->setCouponCodeGenerator($generator);
$rule->setCouponType( Mage_SalesRule_Model_Rule::COUPON_TYPE_AUTO );
 
$count = !empty($parameters['count'])? (int) $parameters['count'] : 1;
$codes = array();
for( $i = 0; $i < $count; $i++ ){
  $coupon = $rule->acquireCoupon();
  $coupon
    ->setType(Mage_SalesRule_Helper_Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED)
    ->save();
 
  $code = $coupon->getCode();
  $codes[] = $code;
}
echo $code;
?>
